-- ============================================================
-- Silver gate: weather_hourly
--
-- Stage:     03 Silver validation, Open-Meteo
-- Runs after: etl/03_silver/20_clean_weather_hourly.sql
-- Target:    `ftw-week-08`.`01-control` DQ results
-- Grain:     one row per check per run
-- Contract:  docs/data_model.md, docs/source_to_target_mapping.md
-- Owner:     TODO
--
-- Integration requires this gate, the Green Taxi gate and the Taxi Zones gate to pass.
-- ============================================================

-- Checks to implement, per docs/validation.md:
--   - row count in vs out against Bronze `open_meteo_weather_raw`
--   - one row per coordinate, local observation hour and weather model, no duplicates
--   - hourly continuity: no gaps or repeats inside the requested window
--   - DST handling: 2026-03-08 has 23 local hours, not 24
--   - temperature, precipitation and weather_code within documented ranges
--   - every WMO code maps to a classification, unknown codes counted
--
-- Write one row per check to the team's DQ results table, then fail the task
-- when a blocking check failed, so downstream stages are skipped:
--
--   SELECT CASE
--            WHEN COUNT_IF(status = 'FAIL') > 0
--            THEN raise_error(concat('Silver weather_hourly gate BLOCKED: ',
--                                    CAST(COUNT_IF(status = 'FAIL') AS STRING),
--                                    ' failed checks'))
--          END
--   FROM `ftw-week-08`.`01-control`.data_quality_results
--   WHERE run_id = dq_run_id;
--
-- Status rule, shared by every gate: INFO stays INFO; fail_count = 0 is PASS;
-- severity FAIL is FAIL; a WARN check above its threshold_pct becomes FAIL.
-- fail_pct and threshold_pct are both percentages.

-- ------------------------------------------------------------
-- Remove this block when the query above is implemented. It keeps an
-- unfinished stage from looking successful in a Databricks job run.
-- ------------------------------------------------------------
SELECT raise_error('90_validate_weather_hourly.sql is not implemented yet');
